issuers page
centrifuge/website pull request #289
Opened 2021-06-30 07:08 UTC by sounak98

2021-06-30 15:24 UTC, armandomistral commented on src/components/AltairHero/index.js
> +              target="_blank"
Don't reintroduce target blank – the page should load in the same window…

2021-06-30 15:32 UTC, sounak98 commented on src/components/AltairHero/index.js
> +              target="_blank"
Yeah, just noticed the new commits and have removed it. This PR is WIP, so don't merge it before the Altair Staking release.

2021-07-12 12:39 UTC, offerijns requested changes

2021-07-12 12:39 UTC, offerijns commented on src/helpers/subgraph.js
> +                  reserve, assetValue
```suggestion
                  reserve, assetValue, totalBorrowsAggregatedAmount
```

2021-07-12 12:39 UTC, offerijns commented on src/helpers/subgraph.js
> +    return sum.add(new BN(pool.assetValue));
```suggestion
    return sum.add(new BN(pool.totalBorrowsAggregatedAmount));
```

2021-07-22 12:43 UTC, sounak98 commented
@Dy-Dedi I have updated the file, looks much better now

2021-07-22 14:24 UTC, merged