feat: add referral bonus stats
centrifuge/website pull request #328
Opened 2021-09-16 21:22 UTC by jpangelle

### Description

This pull request adds the stats dashboard to the staking page. Also adds the total contributions in the header

[Preview Link](https://6143b3f9b3ceec262a8d213f--centrifuge-website.netlify.app/altair/crowdloan)

Screenshots:
![image](https://user-images.githubusercontent.com/28536523/133686829-e32f715f-626a-445c-8821-1122251aa2ad.png)

![image](https://user-images.githubusercontent.com/28536523/133686792-bd1adc3b-9018-48cb-8ca5-8499fd642a7e.png)

2021-09-17 07:17 UTC, armandomistral approved these changes
Looks good to me, @jpangelle!! Thanks

2021-09-21 08:09 UTC, onnovisser approved these changes
👍

2021-09-21 11:54 UTC, alessioscalici requested changes

2021-09-21 11:54 UTC, alessioscalici commented on package.json
> +    "axios": "^0.21.4",
Is there a reason to use `axios` instead of standard `fetch`?

2021-09-21 11:54 UTC, alessioscalici commented on package.json
> +    "bignumber.js": "^9.0.1",
Probably silly question: is it necessary to use BigNumber here? Wouldn' be enough using native `number` type, considering it's for presentation?

2021-09-21 13:05 UTC, alessioscalici commented on package.json
> +    "axios": "^0.21.4",
resolving, I didn't notice this is only used in lambdas 😅

2021-09-21 15:14 UTC, alessioscalici commented on package.json
> +    "bignumber.js": "^9.0.1",
Cool, thanks for the clarification! resolving!

2021-09-21 15:14 UTC, alessioscalici approved these changes

2021-09-29 13:17 UTC, armandomistral approved these changes

2021-09-29 13:52 UTC, alessioscalici approved these changes

2021-10-04 04:49 UTC, closed without merging