Org and Ethics sections
centrifuge/website pull request #507
Opened 2022-10-05 17:31 UTC by onnovisser

Mocking up the Org and Ethics sections of the About Us page

2022-10-06 06:46 UTC, Hornebom requested changes

2022-10-06 06:46 UTC, Hornebom commented on src/pages/about.tsx
> +export default AboutPage
You don't need to create a page. Just add content to `~/content/about-us.json`. Have a look at the `home.json`

2022-10-06 06:46 UTC, Hornebom commented on src/components/Layout.tsx
> +      <Box as="main" pb={200} px={3}>
If `<main>` has a padding-left/right it will be tedious to create full-width sections, like the black one right under the hero on the homepage

2022-10-06 06:46 UTC, Hornebom commented on src/components/BeliefsSection.tsx
> +    <Container>
`as="section"`

2022-10-06 06:46 UTC, Hornebom commented on src/components/HeroVideo.tsx
> +    <Container>
`as="section"`

2022-10-10 10:26 UTC, onnovisser commented on src/components/Layout.tsx
> +      <Box as="main" pb={200} px={3}>
created a new CenterContainer component for this

2022-10-10 10:27 UTC, onnovisser commented on src/components/BeliefsSection.tsx
> +          <Grid columns={[1, 2]} gap={8} rowGap={[4, 10]}>
used roles instead

2022-10-10 10:28 UTC, onnovisser commented on src/pages/about.tsx
> +export default AboutPage
using the about.tsx to mock it up as the json doesn't hot-reload. will put it there later

2022-10-10 13:47 UTC, Hornebom commented on src/components/HeroVideo.tsx
> +          muted
Maybe `loop ` as well

2022-10-10 13:47 UTC, Hornebom commented on src/components/OrgSection.tsx
> +        <Grid columns={[1, 1, 3]} gap={[8, 8, 5]} equalColumns role="list">
`as="ul"`

2022-10-10 13:53 UTC, onnovisser commented on src/components/OrgSection.tsx
> +        <Grid columns={[1, 1, 3]} gap={[8, 8, 5]} equalColumns role="list">
already has `role="list"`

2022-10-12 12:39 UTC, merged